# The numpy.random package

### What do I need to do?

###### required to create a Jupyter [5] notebook explaining the use of the package, including
detailed explanations of at least five of the distributions provided for in the package.
There are four distinct tasks to be carried out in your Jupyter notebook.
1. Explain the overall purpose of the package.
2. Explain the use of the “Simple random data” and “Permutations” functions.
3. Explain the use and purpose of at least five “Distributions” functions.
4. Explain the use of seeds in generating pseudorandom numbers

https://docs.scipy.org/doc/  First Reference

what is numpy.random
http://www.numpy.org/

https://docs.scipy.org/doc/numpy/user/quickstart.html 

## Simple random data


In [ ]:
Simple random data


rand(d0, d1, …, dn)
Random values in a given shape.
randn(d0, d1, …, dn)
Return a sample (or samples) from the “standard normal” distribution.
randint(low[, high, size, dtype])
Return random integers from low (inclusive) to high (exclusive).
random_integers(low[, high, size])
Random integers of type np.int between low and high, inclusive.
random_sample([size])
Return random floats in the half-open interval [0.0, 1.0).
random([size])
Return random floats in the half-open interval [0.0, 1.0).
ranf([size])
Return random floats in the half-open interval [0.0, 1.0).
sample([size])
Return random floats in the half-open interval [0.0, 1.0).
choice(a[, size, replace, p])
Generates a random sample from a given 1-D array
bytes(length)
Return random bytes.
                                                
                                                
                                                https://docs.scipy.org/doc/numpy/reference/routines.random.html

## Permutations

In [ ]:
Permutations


shuffle(x)
Modify a sequence in-place by shuffling its contents.
permutation(x)
Randomly permute a sequence, or return a permuted range.  https://docs.scipy.org/doc/numpy/reference/routines.random.html


In [1]:
##What is numpy first of all



### Seed

##### The numpy random functionality is important in that in order to create a simulation you need to be able to create a set of values to work with. the random submodule " uses a particular algorithm, called the Mersenne Twister, to generate pseudorandom numbers".

"The seed value is used to make the random number predictable.When the value is reset, the same numbers will appear every time. If we do not assign the seed, NumPy automatically selects a random seed value based on the system's random number generator device or on the clock:" https://www.packtpub.com/mapt/book/big_data_and_business_intelligence/9781785285110/2/ch02lvl1sec16/numpy-random-numbers



In [6]:
import numpy as np
np.random.seed(20)


In [7]:
np.random.rand(5)

array([ 0.5881308 ,  0.89771373,  0.89153073,  0.81583748,  0.03588959])

In [8]:
np.random.rand(5)

array([ 0.69175758,  0.37868094,  0.51851095,  0.65795147,  0.19385022])

In [9]:
np.random.seed(20)    # reset seed number

In [10]:
np.random.rand(5)

array([ 0.5881308 ,  0.89771373,  0.89153073,  0.81583748,  0.03588959])

#### When you set the seed number, the random number generator is "locked" in that resetting the seed reverts back to pulling the same random number to begin

#### Numpy is one of main data analysis libraries Python . Others available include Pandas, Matplotlib, PyMongo, and scikit-learn. It is used for Scientific computing in Python and has a number of charactaristics. 

"A powerful N-dimensional array object

Sophisticated (broadcasting) functions for performing array computations

Tools for integrating C/C++ and Fortran code

Useful linear algebra operations, Fourier transformations, and random number capabilities

Besides this, it can also be used as an efficient multidimensional container of generic data. Arbitrary data types can be defined and integrated with a wide variety of databases."https://www.packtpub.com/mapt/book/big_data_and_business_intelligence/9781785285110/1/ch01lvl1sec10/python-libraries-in-data-analysis

